spring.application.name=codeToHire

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/codeToHire
spring.datasource.username=codeToHire
spring.datasource.password=12345

logging.level.org.springframework.security=DEBUG


judge0.url.baseUrl=http://65.1.3.192:2358
